# Session 5 🐍

☀️☀️☀️☀️☀️☀️☀️☀️☀️☀️☀️☀️☀️☀️☀️☀️☀️☀️☀️☀️☀️☀️☀️☀️☀️☀️☀️☀️☀️☀️☀️☀️☀️☀️☀️☀️☀️☀️☀️☀️☀️☀️☀️☀️☀️

***

# 36. NumPy 
NumPy (Numerical Python) is the foundational package for numerical computing in Python. It provides high-performance multidimensional arrays, tools for working with these arrays, and mathematical functions to operate on them.

***

# 37. Performance: 
- Faster than Python lists 
- Vectorized operations: Avoid explicit loops
- Broadcasting: Operations on arrays of different shapes
- Interoperability: Works with Pandas, SciPy, scikit-learn, etc.

***

# 38. Core Concept: ndarray
NumPy's main object is the n-dimensional array (ndarray):

In [1]:
import numpy as np
arr = np.array([1, 2, 3])  # 1D array
print(type(arr))   

<class 'numpy.ndarray'>


***

# 39. Key Properties

***

## 39-1. ndim
Number of dimensions

In [3]:
arr.ndim

1

***

## 39-2. shape	
Tuple of array dimensions	

In [4]:
arr.shape

(3,)

***

## 39-3. dtype	
Data type of elements

In [5]:
arr.dtype

dtype('int32')

***

## 39-4. size	
Total number of elements

In [6]:
arr.size

3

***

# 40. Creating Arrays

***

## 40-1. From Python Lists

In [2]:
np.array([1, 2, 3])          # 1D
np.array([[1, 2], [3, 4]])   # 2D

array([[1, 2],
       [3, 4]])

***

## 40-2. Special Arrays

***

### 40-2-1. np.zeros( )	
Array filled with 0s

In [7]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

***

### 40-2-2. np.ones( )	
Array filled with 1s

In [8]:
np.ones(5)

array([1., 1., 1., 1., 1.])

***

### 40-2-3. np.arange( )	
Like Python's range( )

In [9]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

***

### 40-2-4. np.linspace( )	
Evenly spaced numbers

In [10]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

***

### 40-2-5. np.random.rand( )	
Random values [0, 1)

In [11]:
np.random.rand(3, 3)

array([[0.98362887, 0.74653632, 0.70035858],
       [0.5741457 , 0.5476341 , 0.65049618],
       [0.04187802, 0.01523584, 0.7158664 ]])

***

# 41. Array Operations

***

## 41-1. Arithmetic (Element-wise)

In [12]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)  
print(a * 2)  

[5 7 9]
[2 4 6]


***

## 41-2. Matrix Operations

In [13]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(A @ B)  # Matrix multiplication
print(np.dot(A, B))  # Alternative

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


***

## 41-3. Aggregations

In [14]:
arr = np.array([1, 2, 3])
print(np.sum(arr))    
print(np.mean(arr))   
print(np.max(arr))    

6
2.0
3


***

# 42. Indexing & Slicing

***

## 42-1. 1D Arrays (Like Python Lists)

In [15]:
arr = np.array([1, 2, 3, 4])
print(arr[1])    
print(arr[1:3])  

2
[2 3]


***

## 42-2. 2D Arrays

In [17]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr[0, 1])     # Row 0, Column 1
print(arr[:, 1])     # All rows, Column 1

2
[2 5]


***

## 42-3. Boolean Indexing

In [18]:
arr = np.array([1, 2, 3, 4])
print(arr[arr > 2])  

[3 4]


***

# 43. Reshaping Arrays

In [19]:
arr = np.arange(6)
print(arr.reshape(2, 3))  
print(arr.T)              # Transpose

[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]


***

# 44. Universal Functions (ufuncs)
Fast element-wise operations:

In [20]:
arr = np.array([1.1, 2.2, 3.3])
print(np.sqrt(arr))   # Square root
print(np.exp(arr))    # Exponential
print(np.sin(arr))    # Trigonometric

[1.04880885 1.4832397  1.81659021]
[ 3.00416602  9.0250135  27.11263892]
[ 0.89120736  0.8084964  -0.15774569]


***

# 45. Saving & Loading Arrays

In [ ]:
arr = np.array([1, 2, 3])
np.save('my_array.npy', arr)  # Save
loaded = np.load('my_array.npy')  # Load

***

# 46. Comparing NumPy & Pandas

|Feature	|NumPy	|Pandas   |
|-----------|-------|---------|
|Data Structure	|ndarray	|DataFrame/Series|
|Use Case	|Math operations	|Data analysis|
|Indexing	|Numerical	|Label-based|
|Missing Data	|Not supported	|Supported (NaN)|

***

***

# Some Excercises

**1.**  Create these arrays using NumPy:
- A 1D array of even numbers from 2 to 20
- A 3x3 identity matrix
- A 2x4 array filled with random floats between 5 and 10

___

**2.** Given: arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

Find:
- Number of dimensions
- Shape
- Total elements
- Data type

---

**3.**  For arrays:

A = np.array([1, 2, 3])

B = np.array([4, 5, 6])

Calculate:
- Element-wise sum
- Dot product
- (A² + B³) / 2

---

**4.**  Given: matrix = np.arange(1, 26).reshape(5, 5)

Extract:
- The second column
- The sub-matrix from rows 1-3 and columns 2-4
- All elements > 15

***

**5.** Convert:
- A 1D array of 12 elements into 3x4 matrix
- A 3D array (2x3x4) into 2D (6x4)
- Back to original shape without storing dimensions

***

**6.** Compare execution time of:
- NumPy sum vs Python sum on 1M elements
- NumPy vectorized operation vs Python loop for element-wise multiplication

***

**7.** Exercise:
- Save three different arrays to a single .npz file
- Load them back while verifying data integrity
- Save one array in text format and binary format, compare file sizes

***

**8.** Given a dataset:
- Load it in both NumPy and Pandas

Compare:
- Memory usage
- Operation speed (e.g., mean calculation)
- Handling missing values

***

#                                                        🌞 https://github.com/AI-Planet 🌞